<Project>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Version>2.0.3</Version>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
</Project>
