<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <AssemblyName>RenomearTudo</AssemblyName>
    <RootNamespace>RenomearTudo.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>RenomearTudo.App.Program</StartupObject>
    <ApplicationIcon Condition="Exists('Assets\RenomearTudo.ico')">Assets\RenomearTudo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RenomearTudo.Core\RenomearTudo.Core.csproj" />
  </ItemGroup>
</Project>
