<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>RenomearTudo.Core</AssemblyName>
    <RootNamespace>RenomearTudo.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\GENEROS.TXT" />
  </ItemGroup>
</Project>
